worldin/main/events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('calendar/city=<str:selected_city>/', views.event_calendar, name='event_calendar'),
    path('create/city=<str:selected_city>/', views.create_event, name='create_event'),
    path('edit/<int:event_id>/', views.edit_event, name='edit_event'),
    path('detail/<int:event_id>/', views.event_detail, name='event_detail'),
    path('<int:event_id>/join/', views.join_event, name='join_event'),
]

worldin/main/market/urls.py
from django.urls import path
from . import views

app_name = 'market'


urlpatterns = [
    path('my_market_profile/', views.my_market_profile, name='my_market_profile'),
    path('my_market_profile/ratings', views.my_market_ratings, name='my_market_ratings'),
    path('my_market_profile/add_product', views.add_product, name='add_product'),
    path('product_details/<int:product_id>/', views.product_details, name='product_details'),
    path('product/<int:product_id>/send_message/', views.send_message, name='send_message'),
    path('renting/<int:renting_id>/send_message/', views.send_message_renting, name='send_message_renting'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete_image/<int:product_id>/<int:image_id>/', views.delete_product_image, name='delete_product_image'),
    path('my_market_profile/add_renting', views.add_renting, name='add_renting'),
    path('renting_details/<int:renting_id>/', views.renting_details, name='renting_details'),
    path('delete_renting/<int:renting_id>/', views.delete_renting, name='delete_renting'),
    path('market/profile/user/<str:username>/', views.market_profile_other_user, name='market_profile_other_user'),
    path('edit_renting/<int:renting_id>/', views.edit_renting, name='edit_renting'),
    path('market/products/city=<str:selected_city>/', views.main_market_products, name="main_market_products"),
    path('market/rentings/city=<str:selected_city>/', views.main_market_rentings, name="main_market_rentings"),
    path('highlight_product/<int:product_id>/', views.highlight_product, name='highlight_product'),
    path('highlight_renting/<int:renting_id>/', views.highlight_renting, name='highlight_renting'),
    path('create-checkout-session-renting/<int:renting_id>/', views.create_checkout_session_renting, name='create_checkout_session_renting'),
    path('create-checkout-session-product/<int:product_id>/', views.create_checkout_session_product, name='create_checkout_session_product'),
    path('payment-success-product/', views.payment_success_product, name='payment_success_product'),
    path('payment-success-renting/', views.payment_success_renting, name='payment_success_renting'),
    path('payment-cancel/', views.payment_cancel, name='payment_cancel'),
    path('update_product_highlight_status/', views.update_product_highlight_status, name='update_product_highlight_status'),
    path('update_renting_highlight_status/', views.update_renting_highlight_status, name='update_renting_highlight_status'),
    path('book-product/<int:product_id>/', views.book_product, name='book_product'),
    path('unbook-product/<int:product_id>/', views.unbook_product, name='unbook_product'),
    path('sell-product/<int:product_id>/', views.sell_product, name='sell_product'),
    path('book-renting/<int:renting_id>/', views.book_renting, name='book_renting'),
    path('unbook-renting/<int:renting_id>/', views.unbook_renting, name='unbook_renting'),
    path('sell-renting/<int:renting_id>/', views.sell_renting, name='sell_renting'),
    path('market/profile/ratings/user/<str:username>/', views.other_user_ratings, name='other_user_ratings'),


]

worldin/main/turism/urls.py
from django.urls import path
from . import views

app_name = 'turism'

urlpatterns = [
    path('city_map/<str:city_name>/', views.city_map, name='city_map'),
]

worldin/worldin/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('policy/', views.policy, name='policy'),
    path('usage/', views.usage, name='usage'),
    path('admin/', admin.site.urls),
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('confirm_account/', views.confirm_account, name='confirm_account'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html', 
        email_template_name='registration/password_reset_email.html', 
        subject_template_name='registration/password_reset_subject.txt', 
        extra_context={'domain':'localhost:8000'}), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', extra_context={'domain':'localhost:8000'}), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('logout/', views.logout_view, name='logout'),
    path('world/', views.world_page, name='world'),
    path('accounts/', include('allauth.urls')),
    path('my_profile/', views.profile, name='my_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/profile_settings/', views.profile_settings, name='profile_settings'),
    path('profile/profile_settings/delete_account', views.delete_account, name='delete_account'),
    path('profile/user/<str:username>/followers_count/', views.followers_count, name='followers_count'),
    path('search/', views.search_users, name='search_users'),
    path('profile/user/<str:username>/', views.other_user_profile, name='other_user_profile'),
    path('followers_and_following/user/<str:username>/', views.followers_and_following, name='followers_and_following'),
    path('remove_follower/<int:follower_id>/', views.remove_follower, name='remove_follower'),
    path('unfollow_user/<int:following_id>/', views.unfollow_user, name='unfollow_user'),
    path('follow_requests/', views.follow_requests, name='follow_requests'),
    path('accept_follow_request/<int:request_id>/', views.accept_follow_request, name='accept_follow_request'),
    path('reject_follow_request/<int:request_id>/', views.reject_follow_request, name='reject_follow_request'),
    path('update-city/', views.update_city, name='update_city'),
    path('marketplace/', include('main.market.urls', namespace='market')),
    path('community/', include('main.community.urls', namespace='community')),
    path('events/', include('main.events.urls', namespace='events')),
    path('turism/', include('main.turism.urls', namespace='turism')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldin/main/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count
from .models import Chat, ChatMember, ChatRequest, GroupChat, Message
from main.models import Follow, CustomUser, FollowRequest
from main.views import alertas_completar_perfil
from main.views import city_data
from itertools import chain
from django.db import models
from .forms import EditGroupForm

@login_required
def all_chats(request):
    complete_profile_alerts = alertas_completar_perfil(request)
    pending_requests_count = FollowRequest.objects.filter(receiver=request.user, status='pending').count()

    pending_chat_requests_count = ChatRequest.objects.filter(receiver=request.user, status='pending').count()

    private_chats = Chat.objects.filter(Q(user1=request.user) | Q(user2=request.user)).annotate(
        unread_count=Count('messages', filter=Q(messages__is_read=False) & ~Q(messages__sender=request.user))
    )

    all_groups_chats = GroupChat.objects.filter(members__user=request.user).exclude(name=request.user.city).annotate(
        unread_count=Count('group_messages', filter=Q(group_messages__is_read=False) & ~Q(group_messages__sender=request.user))
    )

    pinned_chat = GroupChat.objects.filter(name=request.user.city).first()

    city_info = city_data.get(request.user.city, {})
    country = city_info.get('country', 'Desconocido')
    flag_image = city_info.get('flag', '')

    all_my_chats = [pinned_chat] + sorted(
        chain(
            private_chats.annotate(last_message_date=models.Max('messages__timestamp')),
            all_groups_chats.annotate(last_message_date=models.Max('group_messages__timestamp'))
        ),
        key=lambda chat: chat.last_message_date if chat.last_message_date else chat.created_at,
        reverse=True
    )
    total_unread_count_only_chats = sum(chat.unread_count for chat in private_chats) + sum(chat.unread_count for chat in all_groups_chats)

    total_unread_count = sum(chat.unread_count for chat in private_chats) + sum(chat.unread_count for chat in all_groups_chats) + pending_chat_requests_count

    return render(request, 'community/all_chats.html', {
        'complete_profile_alerts': complete_profile_alerts,
        'pending_requests_count': pending_requests_count,
        'private_chats': private_chats,
        'all_my_chats': all_my_chats,
        'country': country,
        'flag_image': flag_image,
        'pending_chat_requests_count': pending_chat_requests_count,
        'total_unread_count': total_unread_count,
        'total_unread_count_only_chats': total_unread_count_only_chats
    })

@login_required
def create_private_chat(request):
    query = request.GET.get('q')
    users = CustomUser.objects.exclude(username=request.user.username)
    error_messages = []
    
    # Filtrar usuarios por nombre si existe un query
    if query:
        users = users.filter(username__icontains=query)

    if request.method == 'POST':
        selected_user_id = request.POST.get('selected_user')
        if not selected_user_id:
            error_messages.append('Selecciona a un usuario para poder iniciar un chat')
            return render(request, 'community/create_chat.html', {'users': users, 'error_messages': error_messages})
        
        initial_message = request.POST.get('initial_message', '')
        if initial_message == '':
            error_messages.append('Escribe un mensaje inicial para la solicitud de chat')
            return render(request, 'community/create_chat.html', {'users': users, 'error_messages': error_messages})
        
        else:
            initial_message = request.POST.get('initial_message', '')

            # Obtener el usuario seleccionado
            selected_user = get_object_or_404(CustomUser, id=selected_user_id)

            if Chat.objects.filter(Q(user1=request.user, user2=selected_user) | Q(user1=selected_user, user2=request.user)).exists():
                error_messages.append('Ya existe un chat activo con este usuario.')
                return render(request, 'community/create_chat.html', {'users': users, 'error_messages': error_messages})

            # Verificar Follow mutua
            follows_mutually = Follow.objects.filter(
                follower=request.user, following=selected_user
            ).exists() and Follow.objects.filter(
                follower=selected_user, following=request.user
            ).exists()

            if follows_mutually:
                # Si hay follow mutuo, crear un chat directamente
                if Chat.objects.filter(
                    user1=request.user, user2=selected_user
                ).exists():
                    error_messages.append('Ya existe un chat activo con este usuario.')
                    return render(request, 'community/create_chat.html', {'users': users, 'error_messages': error_messages})
                
                else:
                    chat, created = Chat.objects.get_or_create(
                        user1=request.user, user2=selected_user, initial_message=initial_message
                    )
                    # Redirigir a la página del chat (ejemplo)
                    return redirect('community:all_chats')
            else:
                existing_request = ChatRequest.objects.filter(
                    (Q(sender=request.user) & Q(receiver=selected_user) & Q(group_chat__isnull=True)) |
                    (Q(sender=selected_user) & Q(receiver=request.user) & Q(group_chat__isnull=True))
                ).order_by('-created_at').first()

                if existing_request:
                    # Si la solicitud existe, comprobar su estado
                    if existing_request.status in ['accepted', 'pending']:
                        error_messages.append('Ya existe una solicitud pendiente o aceptada entre estos usuarios.')
                        return render(request, 'community/create_chat.html', {'users': users, 'error_messages': error_messages})
                    elif existing_request.status == 'rejected':
                        # Si la solicitud fue rechazada, se puede crear una nueva
                        ChatRequest.objects.create(
                            sender=request.user,
                            receiver=selected_user,
                            initial_message=initial_message
                        )
                        return redirect('community:all_chats')
                else:
                    # Si no existe una solicitud previa, crear una nueva
                    ChatRequest.objects.create(
                        sender=request.user,
                        receiver=selected_user,
                        initial_message=initial_message
                    )
                    return redirect('community:all_chats')
    return render(request, 'community/create_chat.html', {'users': users, 'error_messages': error_messages})

@login_required
def accept_chat_request(request, request_id):
    chat_request = get_object_or_404(ChatRequest, id=request_id, receiver=request.user)
    message = ""
    if chat_request.status == 'pending':
        if chat_request.product:
            initial = "He abierto este chat para hablar sobre el producto"
            chat = Chat.objects.create(user1=chat_request.sender, user2=chat_request.receiver, initial_message=initial)
            message = Message.objects.create(chat=chat, sender=chat_request.sender, content=chat_request.initial_message, product=chat_request.product)
            chat_request.status = 'accepted'
            chat_request.save()
        elif chat_request.renting:
            initial = "He abierto este chat para hablar sobre el alquiler"
            chat = Chat.objects.create(user1=chat_request.sender, user2=chat_request.receiver, initial_message=initial)
            message = Message.objects.create(chat=chat, sender=chat_request.sender, content=chat_request.initial_message, renting=chat_request.renting)
            chat_request.status = 'accepted'
            chat_request.save()
        elif chat_request.group_chat:
            ChatMember.objects.create(group_chat=chat_request.group_chat, user=chat_request.receiver, user_type='normal')
            chat_request.status = 'accepted'
            chat_request.save()
            Message.objects.create(
            group_chat=chat_request.group_chat,
            sender=request.user,
            content=f'El usuario @{request.user} se ha unido al grupo.',
            is_system_message=True
        )
        elif chat_request.is_delete_request:
            chat = Chat.objects.filter(
                Q(user1=chat_request.sender, user2=chat_request.receiver) |
                Q(user1=chat_request.receiver, user2=chat_request.sender)
            ).first()
            if chat:
                chat.delete()
            chat_request.status = 'accepted'
            chat_request.save()
        else:
            Chat.objects.create(user1=chat_request.sender, user2=chat_request.receiver, initial_message=chat_request.initial_message)
            chat_request.status = 'accepted'
            chat_request.save()
    return redirect('community:chat_requests')

@login_required
def reject_chat_request(request, request_id):
    chat_request = get_object_or_404(ChatRequest, id=request_id, receiver=request.user)
    if chat_request.status == 'pending':
        chat_request.status = 'rejected'
        chat_request.save()
    return redirect('community:chat_requests')

@login_required
def chat_requests(request):
    complete_profile_alerts = alertas_completar_perfil(request)
    pending_requests_count = ChatRequest.objects.filter(receiver=request.user, status='pending').count()
    
    pending_requests = request.user.chat_requests_received.filter(status='pending')

    my_requests = request.user.chat_requests_sent.filter().order_by('-created_at')

    return render(request, 'community/chat_requests.html', {

worldin/main/templates/market/add_renting.html
{% extends "main/sidebar.html" %}

{% block title %}Publicar alquiler{% endblock %}

{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=NTR&family=Palanquin:wght@100;200;300;400;500;600;700&family=Work+Sans:wght@500&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Work Sans', sans-serif;
            color: #6a4fb8;
            margin: 0; /* Eliminar el margen */
            padding: 0; /* Eliminar el padding */
            overflow-x: hidden;
        }
        .profile-container {
            display: flex;
            flex-direction: column;
            max-width: 100%;
            padding: 0;
        }

        @media (max-width: 767px) {
            .profile-top {
                flex-direction: column;
                text-align: center;
            }
        }

        .profile-top {
            background-color: #6a4fb8;
            color: white;
            padding: 20px;
        }

        .links-section {
            text-align: center;
            display: flex;
            gap: 50px;
        }

        .link-section a {
            text-decoration: none;
            color: #007bff;
            font-weight: bold;
            cursor: pointer;
            transition: color 0.3s ease;
        }

        .link-item:hover {
            color: #0056b3;
        }

        .btn-products-link {
            color: #6a4fb8;
            background-color: white;
            border: 2px solid #6a4fb8;
            border-radius: 25px;
            padding: 10px 20px;
            text-decoration: none;
            display: inline-block;
            text-align: center;
            font-weight: bold;
        }

        .btn-ratings-link {
            color: white;
            background-color: #6a4fb8;
            border: 2px solid white;
            border-radius: 25px;
            padding: 10px 20px;
            text-decoration: none;
            display: inline-block;
            text-align: center;
            font-weight: bold;
        }

        .btn-ratings-link:hover {
            background-color: #6a4fb8;
            color: white;
            border-color: #6a4fb8;
        }

        .bi-arrow-left-short {
            font-size: 2em;
        }

        .profile-section {
            text-align: center;
            padding: 40px;
        }

        .image-upload-container {
            display: flex;
            gap: 15px;
            padding: 20px;
            overflow-x: auto; /* Habilitar scroll horizontal */
            white-space: nowrap; /* Evitar que los elementos se rompan en línea */
        }
        
        .image-upload-box {
            position: relative;
            flex: 0 0 auto;
            width: 250px;
            height: 250px;
            border: 2px dashed #6a4fb8;
            border-radius: 20%;
            display: flex;
            justify-content: center;
            align-items: center;
            cursor: pointer;
        }

        @media (max-width: 767px) {
            .image-upload-container {
                max-width: 100%; /* Limitar el ancho al contenedor padre */
                overflow-x: auto;
                padding: 10px;
            }
        
            .image-upload-box {
                flex: 0 0 auto;
                width: 250px; /* Tamaño reducido para pantallas pequeñas */
                height: 250px;
            }
        }

        .image-upload-box img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .image-upload-box .plus-icon {
            font-size: 3em;
            color: #6a4fb8;
        }

        .alert {
            font-size: 16px;
        }

        .image-upload-container input[type="file"] {
            display: none;
        }

        .form-group{
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            text-align: center;
        }

        .btn-group-toggle .btn {
            margin: 5px;
            padding: 10px 20px;
            font-size: 18px;
            border-radius: 10px;
            border-color:#786dce;
            color:#786dce;
          }

          .btn-group-toggle .btn:hover {
            background-color: #786dce !important; 
            color: white !important; 
            border-color: white !important;
          }
      
          .btn-group-toggle .btn.active {
            background-color: #786dce !important; 
            color: white !important; 
            border-color: white !important; 
          }
    </style>
</head>

<body>
    <div class="container-fluid profile-container">
        <div class="profile-top d-flex justify-content-between align-items-center">
            <div>
                <a href="{% url 'market:my_market_profile' %}" class="btn btn-primary bi-arrow-left-short d-none d-md-block" style="background-color: transparent; border-color: white;"><h3 style="font-size:12px;">Mi perfil de mercado</h3></a>
            </div>
            
            <div class="links-section d-flex justify-content-center align-items-center">
                <h2>ELIGE QUÉ PUBLICAR:</h2>
                <div class="text-center">
                    <a href="#" class="btn-products-link">PUBLICAR UN ANUNCIO DE ALQUILER</a>
                </div>
                <div class="text-center">
                    <a href="{% url 'market:add_product' %}" class="btn-ratings-link">PUBLICAR UN PRODUCTO</a>
                </div> 
            </div>
        </div>
        

        <div class="profile-section mb-5">
            <h2>PUBLICAR NUEVO ALQUILER</h2>
            <p class="mt-3">
                Este alquiler se publicará en el <strong>mercado de {{ request.user.city }}</strong><br>
                Para publicar artículos en otro mercado, <a href="{% url 'edit_profile' %}">cambia la ciudad de residencia de tu perfil</a>
            </p>
            
            {% if error_messages %}
                <div class="alert alert-danger" style="font-size:18px;" role="alert">
                    {% for message in error_messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
            {% endif %}
            
            <form action="{% url 'market:add_renting' %}" method="post" enctype="multipart/form-data" class="profile-section">
                {% csrf_token %}
                <div class="form-group mt-5">
                    <h4 for="images"><strong>Imágenes del alquiler (al menos 1): *</strong></h4>
                    <p><i class="bi bi-info-circle-fill"></i> Publicar más imágenes dará más seguridad a los futuros inquilinos.</p>
                    <div class="image-upload-container">
                        {% for form in formset %}
                            <div class="image-upload-box" onclick="document.getElementById('file-input-{{ forloop.counter0 }}').click()">
                                <i class="bi-plus plus-icon" id="plus-icon-{{ forloop.counter0 }}"></i>
                                {{ form.image }}
                                <input type="file" id="file-input-{{ forloop.counter0 }}" name="form-{{ forloop.counter0 }}-image" accept="image/*" onchange="previewImage2(event, {{ forloop.counter0 }})">
                                <img id="image-preview-{{ forloop.counter0 }}" style="display: none;">
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <input type="hidden" name="form-TOTAL_FORMS" value="{{ formset.total_form_count }}">
                <input type="hidden" name="form-INITIAL_FORMS" value="{{ formset.initial_form_count }}">
                <div class="form-group">
                    <h4 for="name"><strong>Título: *</strong></h4>
                    <input type="text" class="form-control" id="title" name="title" value="{{ form.title.value|default:'' }}">
                </div>
        
                <div class="form-group">
                    <h4 for="description"><strong>Descripción: *</strong></h4>
                    <textarea class="form-control" id="description" name="description" rows="3">{{ form.description.value|default:'' }}</textarea>
                </div>

                <div class="form-group">
                    <h4 for="location"><strong>Dirección: *</strong></h4>
                    <p><i class="bi bi-info-circle-fill"></i> Para mayor precisión, se recomienda añadir número y piso.</p>
                    <input type="text" class="form-control" id="location" name="location" value="{{ form.location.value|default:'' }}">
                </div>

                <div class="form-group">
                    <h4 for="location"><strong>Metros cuadrados: *</strong></h4>
                    <input type="number" class="form-control" id="square_meters" name="square_meters" value="{{ form.square_meters.value|default:'' }}" style="width:30%;">
                </div>

                <div class="form-group">
                    <h4 for="rooms"><strong>Número de habitaciones: *</strong></h4>
                    <p><i class="bi bi-info-circle-fill"></i> Se considera habitación aquel lugar equipado con al menos una cama.</p>
                    <input type="number" class="form-control" id="rooms" name="rooms" value="{{ form.rooms.value|default:'' }}" style="width:30%;">
                </div>

                <div class="form-group">
                    <h4 for="max_people"><strong>Número máximo de personas admitidas: *</strong></strong></h4>
                    <input type="number" class="form-control" id="max_people" name="max_people" value="{{ form.max_people.value|default:'' }}" style="width:30%;">
                </div>

                <div class="form-group">
                    <h4 for="price"><strong>Precio/mes: *</strong></h4>
                    <p><i class="bi bi-info-circle-fill"></i> Al estar publicando este anuncio en el <strong>mercado de {{ request.user.city }}</strong>, la moneda será <strong>{{ money }}</strong></p>
                    <input type="number" class="form-control" id="price" name="price" value="{{ form.price.value|default:'' }}" style="width:30%;">
                </div>

                <div class="form-group">
                    <h4 for="features"><strong>Características:</strong></h4>
                    <p><i class="bi bi-info-circle-fill"></i> Si tu vivienda cuenta con algunas características que no aparezcan abajo, no te olvides de añadirlas en la descripción del anuncio.</p>
                    <div class="btn-group-toggle" data-toggle="buttons">
                        {% for feature in available_features %}
                            <label class="btn btn-outline-primary {% if feature in rental.features.all %} active {% endif %}">
                                <input type="checkbox" name="features" value="{{ feature.id }}" autocomplete="off"
                                    {% if feature in rental.features.all %} checked {% endif %}> {{ feature.feature }}
                            </label>
                        {% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary mt-5" style="background-color:#786dce; color:white; border-color:white; margin-bottom:4%; font-size:22px;">Publicar</button>

                </div>

                

            </form>
        </div>
    </div>
    <script>
        function previewImage2(event, index) {
            const input = event.target;
            const preview = document.getElementById(`image-preview-${index}`);
            const plusIcon = document.getElementById(`plus-icon-${index}`);

            if (input.files && input.files[0]) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    preview.src = e.target.result;
                    preview.style.display = 'block';
                    plusIcon.style.display = 'none';
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
    <script>
        $(document).ready(function() {
          // Manejo de botones toggle para checkboxes
          $('.btn-group-toggle input[type="checkbox"]').change(function() {
            if ($(this).is(':checked')) {
              $(this).parent().addClass('active');
            } else {
              $(this).parent().removeClass('active');
            }
          });
        });
      </script>
        
</body>
{% endblock %}