worldin/main/events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('calendar/city=<str:selected_city>/', views.event_calendar, name='event_calendar'),
    path('create/city=<str:selected_city>/', views.create_event, name='create_event'),
    path('edit/<int:event_id>/', views.edit_event, name='edit_event'),
    path('detail/<int:event_id>/', views.event_detail, name='event_detail'),
    path('<int:event_id>/join/', views.join_event, name='join_event'),
]

worldin/main/market/urls.py
from django.urls import path
from . import views

app_name = 'market'


urlpatterns = [
    path('my_market_profile/', views.my_market_profile, name='my_market_profile'),
    path('my_market_profile/ratings', views.my_market_ratings, name='my_market_ratings'),
    path('my_market_profile/add_product', views.add_product, name='add_product'),
    path('product_details/<int:product_id>/', views.product_details, name='product_details'),
    path('product/<int:product_id>/send_message/', views.send_message, name='send_message'),
    path('renting/<int:renting_id>/send_message/', views.send_message_renting, name='send_message_renting'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete_image/<int:product_id>/<int:image_id>/', views.delete_product_image, name='delete_product_image'),
    path('my_market_profile/add_renting', views.add_renting, name='add_renting'),
    path('renting_details/<int:renting_id>/', views.renting_details, name='renting_details'),
    path('delete_renting/<int:renting_id>/', views.delete_renting, name='delete_renting'),
    path('market/profile/user/<str:username>/', views.market_profile_other_user, name='market_profile_other_user'),
    path('edit_renting/<int:renting_id>/', views.edit_renting, name='edit_renting'),
    path('market/products/city=<str:selected_city>/', views.main_market_products, name="main_market_products"),
    path('market/rentings/city=<str:selected_city>/', views.main_market_rentings, name="main_market_rentings"),
    path('highlight_product/<int:product_id>/', views.highlight_product, name='highlight_product'),
    path('highlight_renting/<int:renting_id>/', views.highlight_renting, name='highlight_renting'),
    path('create-checkout-session-renting/<int:renting_id>/', views.create_checkout_session_renting, name='create_checkout_session_renting'),
    path('create-checkout-session-product/<int:product_id>/', views.create_checkout_session_product, name='create_checkout_session_product'),
    path('payment-success-product/', views.payment_success_product, name='payment_success_product'),
    path('payment-success-renting/', views.payment_success_renting, name='payment_success_renting'),
    path('payment-cancel/', views.payment_cancel, name='payment_cancel'),
    path('update_product_highlight_status/', views.update_product_highlight_status, name='update_product_highlight_status'),
    path('update_renting_highlight_status/', views.update_renting_highlight_status, name='update_renting_highlight_status'),
    path('book-product/<int:product_id>/', views.book_product, name='book_product'),
    path('unbook-product/<int:product_id>/', views.unbook_product, name='unbook_product'),
    path('sell-product/<int:product_id>/', views.sell_product, name='sell_product'),
    path('book-renting/<int:renting_id>/', views.book_renting, name='book_renting'),
    path('unbook-renting/<int:renting_id>/', views.unbook_renting, name='unbook_renting'),
    path('sell-renting/<int:renting_id>/', views.sell_renting, name='sell_renting'),
    path('market/profile/ratings/user/<str:username>/', views.other_user_ratings, name='other_user_ratings'),


]

worldin/main/turism/urls.py
from django.urls import path
from . import views

app_name = 'turism'

urlpatterns = [
    path('city_map/<str:city_name>/', views.city_map, name='city_map'),
]

worldin/worldin/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('policy/', views.policy, name='policy'),
    path('usage/', views.usage, name='usage'),
    path('admin/', admin.site.urls),
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('confirm_account/', views.confirm_account, name='confirm_account'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html', 
        email_template_name='registration/password_reset_email.html', 
        subject_template_name='registration/password_reset_subject.txt', 
        extra_context={'domain':'localhost:8000'}), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', extra_context={'domain':'localhost:8000'}), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('logout/', views.logout_view, name='logout'),
    path('world/', views.world_page, name='world'),
    path('accounts/', include('allauth.urls')),
    path('my_profile/', views.profile, name='my_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/profile_settings/', views.profile_settings, name='profile_settings'),
    path('profile/profile_settings/delete_account', views.delete_account, name='delete_account'),
    path('profile/user/<str:username>/followers_count/', views.followers_count, name='followers_count'),
    path('search/', views.search_users, name='search_users'),
    path('profile/user/<str:username>/', views.other_user_profile, name='other_user_profile'),
    path('followers_and_following/user/<str:username>/', views.followers_and_following, name='followers_and_following'),
    path('remove_follower/<int:follower_id>/', views.remove_follower, name='remove_follower'),
    path('unfollow_user/<int:following_id>/', views.unfollow_user, name='unfollow_user'),
    path('follow_requests/', views.follow_requests, name='follow_requests'),
    path('accept_follow_request/<int:request_id>/', views.accept_follow_request, name='accept_follow_request'),
    path('reject_follow_request/<int:request_id>/', views.reject_follow_request, name='reject_follow_request'),
    path('update-city/', views.update_city, name='update_city'),
    path('marketplace/', include('main.market.urls', namespace='market')),
    path('community/', include('main.community.urls', namespace='community')),
    path('events/', include('main.events.urls', namespace='events')),
    path('turism/', include('main.turism.urls', namespace='turism')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldin/main/community/models.py
from django.conf import settings
from django.db import models
from main.market.models import Product, Rental
from main.models import CustomUser

# Modelo para el Chat
class Chat(models.Model):
    user1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='chats_user1', on_delete=models.CASCADE)
    user2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='chats_user2', on_delete=models.CASCADE)
    initial_message = models.TextField(blank=True)
    products = models.ManyToManyField(Product, blank=True, related_name='associated_chats')
    rentings = models.ManyToManyField(Rental, blank=True, related_name='rentings_associated_chats')
    created_at = models.DateTimeField(auto_now_add=True)
    is_group = models.BooleanField(default=False)

    class Meta:
        unique_together = ('user1', 'user2')  # Un chat único entre dos usuarios

    def __str__(self):
        return f"Chat between {self.user1.username} and {self.user2.username}"

class GroupChat(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    image = models.ImageField(upload_to='group_chat_pictures/', blank=True, null=True)
    initial_message = models.TextField(blank=True)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_group = models.BooleanField(default=True)
    is_friends_group = models.BooleanField(default=False)
    is_event_group = models.BooleanField(default=False)
    chat_members = models.ManyToManyField(settings.AUTH_USER_MODEL, through='ChatMember', related_name='group_chats')

    def __str__(self):
        return f"Group Chat: {self.name}"
    
class ChatMember(models.Model):
    USER_TYPE_CHOICES = [
        ('admin', 'Administrador'),
        ('normal', 'Normal'),
        ('external', 'Externo'),
    ]

    group_chat = models.ForeignKey('GroupChat', on_delete=models.CASCADE, related_name='members')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, default='normal')

    def __str__(self):
        return f"{self.user.username} in {self.group_chat.name} ({self.get_user_type_display()})"

    

# Modelo para la solicitud de chat
class ChatRequest(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='chat_requests_sent', on_delete=models.CASCADE)
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='chat_requests_received', on_delete=models.CASCADE)
    initial_message = models.TextField(blank=False)
    group_chat = models.ForeignKey(GroupChat, null=True, blank=True, on_delete=models.CASCADE, related_name='group_requests')
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.SET_NULL, related_name='chatrequests')
    renting = models.ForeignKey(Rental, null=True, blank=True, on_delete=models.SET_NULL, related_name='rentings_chatrequests')
    is_delete_request = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=10,
        choices=[
            ('pending', 'Pendiente'),
            ('accepted', 'Aceptada'),
            ('rejected', 'Rechazada')
        ],
        default='pending'
    )

    def __str__(self):
        return f"Chat request from {self.sender.username} to {self.receiver.username}"
    
class Message(models.Model):
    chat = models.ForeignKey(Chat, null=True, blank=True, related_name='messages', on_delete=models.CASCADE)
    group_chat = models.ForeignKey(GroupChat, null=True, blank=True, on_delete=models.CASCADE, related_name='group_messages')
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.SET_NULL, related_name='product_messages')
    renting = models.ForeignKey(Rental, null=True, blank=True, on_delete=models.SET_NULL, related_name='renting_messages')
    is_system_message = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"Message from {self.sender.username} at {self.timestamp}"

worldin/main/events/models.py
from django.db import models
from django.conf import settings

class Event(models.Model):
    city = models.CharField(max_length=100)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    location = models.CharField(max_length=255)
    start = models.DateTimeField()
    end = models.DateTimeField()
    price = models.FloatField()
    dresscode = models.CharField(max_length=100, blank=True)
    associated_chat = models.ForeignKey('community.GroupChat', on_delete=models.SET_NULL, null=True, blank=True, related_name='events')
    tickets_link = models.URLField(blank=True, null=True)
    max_people = models.PositiveIntegerField(null=True, blank=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='created_events')

    def __str__(self):
        return f"{self.title} - {self.city}"

worldin/main/community/forms.py
from django import forms
from .models import GroupChat

class EditGroupForm(forms.ModelForm):
    class Meta:
        model = GroupChat
        fields = ['name', 'image', 'description']
        labels = {
            'name': 'Nombre del grupo',
            'image': 'Imagen del grupo',
            'description': 'Descripción del grupo',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

worldin/main/turism/views.py
from django.contrib.auth.decorators import login_required
from main.views import city_data 
from django.shortcuts import render
import requests
from main.models import FollowRequest
from main.community.models import ChatRequest, Chat, GroupChat
from django.db.models import Count, Q
from main.views import alertas_completar_perfil
from urllib.parse import quote

def city_conversor(city):
    if city == "La Valeta":
        return "Valletta"
    elif city == "Atenas":
        return "Athens"
    elif city == "Luxemburgo":
        return "Luxembourg"
    elif city == "Roterdam":
        return "Rotterdam"
    elif city == "Viena":
        return "Wien"
    elif city == "Varsovia":
        return "Warsaw"
    elif city == "Oporto":
        return "Porto"
    elif city == "Buenos Aires":
        return "Buenos%20Aires"
    elif city == "Washington D.C.":
        return "Washington"
    elif city == "Nueva Delhi":
        return "New%20Delhi"
    elif city == "Sofia":
        return quote("София")
    elif city == "Copenhague":
        return quote("København")
    elif city == "Brasilia":
        return quote("Brasília")
    elif city == "Praga":
        return "Praha"
    elif city == "Pekín":
        return quote("北京")
    else:
        return city

@login_required
def city_map(request, city_name):
    complete_profile_alerts = alertas_completar_perfil(request)
    pending_requests_count = FollowRequest.objects.filter(receiver=request.user, status='pending').count()

    pending_chat_requests_count = ChatRequest.objects.filter(receiver=request.user, status='pending').count()

    private_chats = Chat.objects.filter(Q(user1=request.user) | Q(user2=request.user)).annotate(
        unread_count=Count('messages', filter=Q(messages__is_read=False) & ~Q(messages__sender=request.user))
    )

    all_groups_chats = GroupChat.objects.filter(members__user=request.user).exclude(name=request.user.city).annotate(
        unread_count=Count('group_messages', filter=Q(group_messages__is_read=False) & ~Q(group_messages__sender=request.user))
    )

    total_unread_count = sum(chat.unread_count for chat in private_chats) + sum(chat.unread_count for chat in all_groups_chats)
    city_info = city_data.get(city_name)

    if not city_info:
        return render(request, 'invalid_city.html', {
            "city_name": city_name,
            "complete_profile_alerts": complete_profile_alerts,
            "pending_requests_count": pending_requests_count,
            "pending_chat_requests_count": pending_chat_requests_count,
            "total_unread_count": total_unread_count,})
    
    # Información adicional
    country = city_info.get('country', 'Desconocido')
    flag_image = city_info.get('flag', '')

    lat, lon = city_info["lat"], city_info["lon"]

    conversor = city_conversor(city_name)

    # URL para Overpass API
    overpass_url = f'https://overpass-api.de/api/interpreter?data=[out:json];area[name="{conversor}"];node["tourism"]["tourism"!~"^(hotel|hostel|motel|picnic_site|camp_site|chalet|viewpoint|apartment|guest_house|attraction|gallery)$"](area);out;'

    response = requests.get(overpass_url)
    data = response.json() if response.status_code == 200 else {"elements": []}

    # Extraer los lugares turísticos
    places = []
    for elem in data["elements"]:
        if "lat" in elem and "lon" in elem:
            tags = elem.get("tags", {})
            places.append({
                "name": tags.get("name", "Lugar turístico"),
                "lat": elem["lat"],
                "lon": elem["lon"],
                "address": f'{tags.get("addr:street", "")} {tags.get("addr:housenumber", "")} {tags.get("addr:postcode", "")}'.strip(),
                "opening_hours": tags.get("opening_hours", "Horario no disponible"),
                "price": tags.get("fee", ""),
                "website": tags.get("website", ""),
                "phone": tags.get("phone", ""),
            })

    return render(request, "turism/city_map.html", {
        "city_name": city_name,
        "lat": lat,
        "lon": lon,
        "places": places,
        "country": country,
        "flag_image": flag_image,
        "complete_profile_alerts": complete_profile_alerts,
        "pending_requests_count": pending_requests_count,
        "pending_chat_requests_count": pending_chat_requests_count,
        "total_unread_count": total_unread_count,
    })

worldin/main/templates/events/edit_event.html
{% extends 'sidebar.html' %}
{% block title %}Editar evento{% endblock %}
{% block content %}
{% load static %}
{% load widget_tweaks %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=NTR&family=Palanquin:wght@100;200;300;400;500;600;700&family=Work+Sans:wght@500&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Work Sans', sans-serif;
            color: #6a4fb8;
            overflow-x:hidden;
        }
        .profile-container {
            display: flex;
            flex-direction: column;
            max-width: 100%; /* Ocupar el máximo ancho disponible */
            padding: 0; /* Sin padding para que ocupe todo el ancho */
        }
        .profile-top {
            background-color: #6a4fb8;
            color: white;
            padding: 20px;
        }
        @media (max-width: 767px) {
            .responsive-margin {
                margin-top: 5%;
                margin-left: 10%;
                margin-right: 10%;
                margin-bottom: 5%;
            }
        }

        @media (min-width: 768px) {
            .responsive-margin {
                margin-top: 5%;
                margin-left: 20%;
                margin-right: 20%;
                margin-bottom: 5%;
            }
        }
    </style>
</head>
<body>
    <div class="container profile-container">
        <div class="profile-top d-flex justify-content-between align-items-center">
            <div>
                <button onclick="goBack()" class="btn btn-secondary bi-arrow-left-short" style="background-color: transparent; border-color: white; font-size: 2em;">
                    <h3 style="font-size:12px;">Volver</h3>
                </button>
            </div>

            <div class="text-center mx-auto">
                <h1><strong>Editar Evento</strong></h1>
                {% if request.user.city %}
                    <h3> 
                    {% if flag_image %}
                        <img src="{% static 'images/'|add:flag_image %}" alt="Bandera de {{ country }}" width="50">
                    {% endif %}  
                    {{ selected_city }}, {{ country }}
                    </h3>
                {% endif %}
            </div>            
        </div>

        
        <div class="responsive-margin">
            {% if error_messages %}
                <div class="alert alert-danger" style="font-size:18px;" role="alert" id="error-alert">
                    {% for message in error_messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
            {% endif %}
            <form method="post" style="width: 100%;">
            {% csrf_token %}
            <div class="form-group mb-3 row align-items-center">
                <label for="id_title" class="col-sm-2 col-form-label" style="color: #6a4fb8; font-size: 1.2em;">{{ form.title.label }}<span style="color:red;"><strong> *</strong></span></label>
                <div class="col-sm-10">
                {{ form.title|add_class:"form-control rounded-pill" }}
                </div>
            </div>
            <div class="form-group mb-3 row align-items-center">
                <label for="id_description" class="col-sm-2 col-form-label" style="color: #6a4fb8; font-size: 1.2em;">{{ form.description.label }}</label>
                <div class="col-sm-10">
                {{ form.description|add_class:"form-control rounded" }}
                </div>
            </div>
            <div class="form-group mb-3 row align-items-center">
                <label for="id_location" class="col-sm-1 text-end" style="color: #6a4fb8; font-size: 1.5em;">
                    <i class="bi bi-geo-alt"></i><span style="color:red;"><strong> *</strong></span>
                </label>
                <div class="col-sm-11">
                    {{ form.location|add_class:"form-control rounded-pill"|attr:"placeholder: Ubicación" }}
                </div>
            </div>
            <div class="form-group mb-3 row align-items-center">
                <label for="id_start" class="col-sm-1 text-end" style="color: #6a4fb8; font-size: 1.5em;" title="Fecha y hora de inicio del evento">
                    <i class="bi bi-clock"></i><span style="color:red;"><strong> *</strong></span>
                </label>
                <div class="col-sm-11">
                    {{ form.start|add_class:"form-control rounded-pill"|attr:"placeholder: Hora de inicio" }}
                </div>
            </div>
            <div class="form-group mb-3 row align-items-center">
                <label for="id_end" class="col-sm-1 text-end" style="color: #6a4fb8; font-size: 1.5em;" title="Fecha y hora de finalización del evento">
                    <i class="bi bi-clock-history"></i><span style="color:red;"><strong> *</strong></span>
                </label>
                <div class="col-sm-11">
                    {{ form.end|add_class:"form-control rounded-pill"|attr:"placeholder: Hora de finalización" }}
                </div>
            </div>
            <div class="form-group mb-3 row align-items-center">
                <label for="id_price" class="col-sm-1 text-end" style="color: #6a4fb8; font-size: 1.5em;">
                    <i class="bi bi-currency-dollar"></i><span style="color:red;"><strong> *</strong></span>
                </label>
                <div class="col-sm-11">
                    {{ form.price|add_class:"form-control rounded-pill"|attr:"placeholder: Precio" }}
                </div>
                <p> El precio es simplemente informativo, la aplicación no recoge pagos en el proceso de inscripción en eventos. 
                    Todo lo relacionado con entradas o tickets a eventos deberá realizarse de manera externa a la aplicación. 
                    Para ello se habilita el campo de enlace para entradas, donde es posible realizar este proceso mediante terceros.</p>

            </div>
            <div class="form-group mb-3 row align-items-center">
                <label for="id_dresscode" class="col-sm-1 text-end" style="color: #6a4fb8; font-size: 1.5em;">
                    <i class="fa-solid fa-shirt"></i>
                </label>
                <div class="col-sm-11">
                    {{ form.dresscode|add_class:"form-control rounded-pill"|attr:"placeholder: Código de vestimenta" }}
                </div>
            </div>
            <div class="form-group mb-3 row align-items-center">
                <label for="id_tickets_link" class="col-sm-1 text-end" style="color: #6a4fb8; font-size: 1.5em;">
                    <i class="bi bi-link"></i>
                </label>
                <div class="col-sm-11">
                    {{ form.tickets_link|add_class:"form-control rounded-pill"|attr:"placeholder: Enlace para entradas" }}
                </div>
            </div>
            <div class="form-group mb-3 row align-items-center">
                <label for="id_max_people" class="col-sm-1 text-end" style="color: #6a4fb8; font-size: 1.5em;">
                    <i class="fa-solid fa-users"></i>
                </label>
                <div class="col-sm-11">
                    {{ form.max_people|add_class:"form-control rounded-pill"|attr:"placeholder: Límite de participantes" }}
                </div>
            </div>
            <button type="submit" class="btn btn-success">Guardar</button>
            <a href="{% url 'events:event_calendar' selected_city=request.user.selected_city %}" class="btn btn-secondary">Cancelar</a>
            </form>
        </div>
        
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
    <script>
        setTimeout(function() {
            var successAlert = document.getElementById('success-alert');
            if (successAlert) {
                successAlert.style.display = 'none';
            }
            var errorAlert = document.getElementById('error-alert');
            if (errorAlert) {
                errorAlert.style.display = 'none';
            }
        }, 4000);
    </script> 
</body>
{% endblock %}