worldin/main/community/urls.py
from django.urls import path
from . import views

app_name = 'community'


urlpatterns = [
    path('all_chats/', views.all_chats, name='all_chats'),
    path('create_private_chat/', views.create_private_chat, name='create_private_chat'),
    path('chat_requests/', views.chat_requests, name='chat_requests'),
    path('accept_chat_request/<int:request_id>/', views.accept_chat_request, name='accept_chat_request'),
    path('reject_chat_request/<int:request_id>/', views.reject_chat_request, name='reject_chat_request'),
    path('chat_detail/<str:username>/', views.chat_detail, name='chat_detail'),
    path('chat/<str:city>/', views.city_group_chat, name='city_group_chat'),
    path('create_group_chat/', views.create_group_chat, name='create_group_chat'),
    path('chat/<str:name>/', views.group_chat_details, name='group_chat_details'),
    path('delete_group/<str:name>/', views.delete_group, name='delete_group'),
    path('chat/<str:username>/request_deletion/', views.request_chat_deletion, name='request_chat_deletion'),
    path('leave_group/<str:name>/', views.leave_group, name='leave_group'),
    path('edit_group/<int:group_id>/', views.edit_group, name='edit_group'),
    path('add_member/<int:group_id>/', views.add_member, name='add_member'),
    path('remove_member/<int:group_id>/<str:username>/', views.remove_member, name='remove_member'),
    path('group/<int:group_id>/make_admin/<str:username>/', views.make_admin, name='make_admin'),
    path('group/<int:group_id>/remove-admin/<str:username>/', views.remove_admin, name='remove_admin'),
]

worldin/main/events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('calendar/city=<str:selected_city>/', views.event_calendar, name='event_calendar'),
    path('create/city=<str:selected_city>/', views.create_event, name='create_event'),
    path('edit/<int:event_id>/', views.edit_event, name='edit_event'),
    path('detail/<int:event_id>/', views.event_detail, name='event_detail'),
    path('<int:event_id>/join/', views.join_event, name='join_event'),
]

worldin/main/market/urls.py
from django.urls import path
from . import views

app_name = 'market'


urlpatterns = [
    path('my_market_profile/', views.my_market_profile, name='my_market_profile'),
    path('my_market_profile/ratings', views.my_market_ratings, name='my_market_ratings'),
    path('my_market_profile/add_product', views.add_product, name='add_product'),
    path('product_details/<int:product_id>/', views.product_details, name='product_details'),
    path('product/<int:product_id>/send_message/', views.send_message, name='send_message'),
    path('renting/<int:renting_id>/send_message/', views.send_message_renting, name='send_message_renting'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete_image/<int:product_id>/<int:image_id>/', views.delete_product_image, name='delete_product_image'),
    path('my_market_profile/add_renting', views.add_renting, name='add_renting'),
    path('renting_details/<int:renting_id>/', views.renting_details, name='renting_details'),
    path('delete_renting/<int:renting_id>/', views.delete_renting, name='delete_renting'),
    path('market/profile/user/<str:username>/', views.market_profile_other_user, name='market_profile_other_user'),
    path('edit_renting/<int:renting_id>/', views.edit_renting, name='edit_renting'),
    path('market/products/city=<str:selected_city>/', views.main_market_products, name="main_market_products"),
    path('market/rentings/city=<str:selected_city>/', views.main_market_rentings, name="main_market_rentings"),
    path('highlight_product/<int:product_id>/', views.highlight_product, name='highlight_product'),
    path('highlight_renting/<int:renting_id>/', views.highlight_renting, name='highlight_renting'),
    path('create-checkout-session-renting/<int:renting_id>/', views.create_checkout_session_renting, name='create_checkout_session_renting'),
    path('create-checkout-session-product/<int:product_id>/', views.create_checkout_session_product, name='create_checkout_session_product'),
    path('payment-success-product/', views.payment_success_product, name='payment_success_product'),
    path('payment-success-renting/', views.payment_success_renting, name='payment_success_renting'),
    path('payment-cancel/', views.payment_cancel, name='payment_cancel'),
    path('update_product_highlight_status/', views.update_product_highlight_status, name='update_product_highlight_status'),
    path('update_renting_highlight_status/', views.update_renting_highlight_status, name='update_renting_highlight_status'),
    path('book-product/<int:product_id>/', views.book_product, name='book_product'),
    path('unbook-product/<int:product_id>/', views.unbook_product, name='unbook_product'),
    path('sell-product/<int:product_id>/', views.sell_product, name='sell_product'),
    path('book-renting/<int:renting_id>/', views.book_renting, name='book_renting'),
    path('unbook-renting/<int:renting_id>/', views.unbook_renting, name='unbook_renting'),
    path('sell-renting/<int:renting_id>/', views.sell_renting, name='sell_renting'),
    path('market/profile/ratings/user/<str:username>/', views.other_user_ratings, name='other_user_ratings'),


]

worldin/main/turism/urls.py
from django.urls import path
from . import views

app_name = 'turism'

urlpatterns = [
    path('city_map/<str:city_name>/', views.city_map, name='city_map'),
]

worldin/worldin/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('policy/', views.policy, name='policy'),
    path('usage/', views.usage, name='usage'),
    path('admin/', admin.site.urls),
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('confirm_account/', views.confirm_account, name='confirm_account'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html', 
        email_template_name='registration/password_reset_email.html', 
        subject_template_name='registration/password_reset_subject.txt', 
        extra_context={'domain':'localhost:8000'}), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', extra_context={'domain':'localhost:8000'}), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('logout/', views.logout_view, name='logout'),
    path('world/', views.world_page, name='world'),
    path('accounts/', include('allauth.urls')),
    path('my_profile/', views.profile, name='my_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/profile_settings/', views.profile_settings, name='profile_settings'),
    path('profile/profile_settings/delete_account', views.delete_account, name='delete_account'),
    path('profile/user/<str:username>/followers_count/', views.followers_count, name='followers_count'),
    path('search/', views.search_users, name='search_users'),
    path('profile/user/<str:username>/', views.other_user_profile, name='other_user_profile'),
    path('followers_and_following/user/<str:username>/', views.followers_and_following, name='followers_and_following'),
    path('remove_follower/<int:follower_id>/', views.remove_follower, name='remove_follower'),
    path('unfollow_user/<int:following_id>/', views.unfollow_user, name='unfollow_user'),
    path('follow_requests/', views.follow_requests, name='follow_requests'),
    path('accept_follow_request/<int:request_id>/', views.accept_follow_request, name='accept_follow_request'),
    path('reject_follow_request/<int:request_id>/', views.reject_follow_request, name='reject_follow_request'),
    path('update-city/', views.update_city, name='update_city'),
    path('marketplace/', include('main.market.urls', namespace='market')),
    path('community/', include('main.community.urls', namespace='community')),
    path('events/', include('main.events.urls', namespace='events')),
    path('turism/', include('main.turism.urls', namespace='turism')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldin/main/events/models.py
from django.db import models
from django.conf import settings

class Event(models.Model):
    city = models.CharField(max_length=100)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    location = models.CharField(max_length=255)
    start = models.DateTimeField()
    end = models.DateTimeField()
    price = models.FloatField()
    dresscode = models.CharField(max_length=100, blank=True)
    associated_chat = models.ForeignKey('community.GroupChat', on_delete=models.SET_NULL, null=True, blank=True, related_name='events')
    tickets_link = models.URLField(blank=True, null=True)
    max_people = models.PositiveIntegerField(null=True, blank=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='created_events')

    def __str__(self):
        return f"{self.title} - {self.city}"

worldin/main/community/forms.py
from django import forms
from .models import GroupChat

class EditGroupForm(forms.ModelForm):
    class Meta:
        model = GroupChat
        fields = ['name', 'image', 'description']
        labels = {
            'name': 'Nombre del grupo',
            'image': 'Imagen del grupo',
            'description': 'Descripción del grupo',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

worldin/main/events/forms.py
from django import forms
from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'location', 'start', 'end', 'price', 'dresscode', 'tickets_link', 'max_people']
        labels = {
            'title': 'Título',
            'description': 'Descripción',
            'location': 'Ubicación',
            'start': 'Fecha y hora de inicio',
            'end': 'Fecha y hora de fin',
            'price': 'Precio',
            'dresscode': 'Código de vestimenta',
            'tickets_link': 'Enlace de compra de entradas',
            'max_people': 'Límite de participantes',
        }
        widgets = {
            'start': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'end': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

worldin/main/market/forms.py
from django import forms
from .models import  Product, Rental, ProductImage, RentalImage
from django.forms import modelformset_factory

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price']

class ProductImageForm(forms.ModelForm):
    delete_image = forms.BooleanField(required=False, label='Eliminar', initial=False)

    class Meta:
        model = ProductImage
        fields = ['image', 'delete_image']

ProductImageFormSet = modelformset_factory(ProductImage, form=ProductImageForm, extra= 3)

class RentalForm(forms.ModelForm):
    class Meta:
        model = Rental
        fields = ['title', 'location', 'description', 'price', 'square_meters', 'rooms', 'max_people']

class RentalImageForm(forms.ModelForm):
    class Meta:
        model = RentalImage
        fields = ['image']

RentalImageFormSet = modelformset_factory(RentalImage, form=RentalImageForm, extra=4)

worldin/main/turism/views.py
from django.contrib.auth.decorators import login_required
from main.views import city_data 
from django.shortcuts import render
import requests
from main.models import FollowRequest
from main.community.models import ChatRequest, Chat, GroupChat
from django.db.models import Count, Q
from main.views import alertas_completar_perfil
from urllib.parse import quote

def city_conversor(city):
    if city == "La Valeta":
        return "Valletta"
    elif city == "Atenas":
        return "Athens"
    elif city == "Luxemburgo":
        return "Luxembourg"
    elif city == "Roterdam":
        return "Rotterdam"
    elif city == "Viena":
        return "Wien"
    elif city == "Varsovia":
        return "Warsaw"
    elif city == "Oporto":
        return "Porto"
    elif city == "Buenos Aires":
        return "Buenos%20Aires"
    elif city == "Washington D.C.":
        return "Washington"
    elif city == "Nueva Delhi":
        return "New%20Delhi"
    elif city == "Sofia":
        return quote("София")
    elif city == "Copenhague":
        return quote("København")
    elif city == "Brasilia":
        return quote("Brasília")
    elif city == "Praga":
        return "Praha"
    elif city == "Pekín":
        return quote("北京")
    else:
        return city

@login_required
def city_map(request, city_name):
    complete_profile_alerts = alertas_completar_perfil(request)
    pending_requests_count = FollowRequest.objects.filter(receiver=request.user, status='pending').count()

    pending_chat_requests_count = ChatRequest.objects.filter(receiver=request.user, status='pending').count()

    private_chats = Chat.objects.filter(Q(user1=request.user) | Q(user2=request.user)).annotate(
        unread_count=Count('messages', filter=Q(messages__is_read=False) & ~Q(messages__sender=request.user))
    )

    all_groups_chats = GroupChat.objects.filter(members__user=request.user).exclude(name=request.user.city).annotate(
        unread_count=Count('group_messages', filter=Q(group_messages__is_read=False) & ~Q(group_messages__sender=request.user))
    )

    total_unread_count = sum(chat.unread_count for chat in private_chats) + sum(chat.unread_count for chat in all_groups_chats)
    city_info = city_data.get(city_name)

    if not city_info:
        return render(request, 'invalid_city.html', {
            "city_name": city_name,
            "complete_profile_alerts": complete_profile_alerts,
            "pending_requests_count": pending_requests_count,
            "pending_chat_requests_count": pending_chat_requests_count,
            "total_unread_count": total_unread_count,})
    
    # Información adicional
    country = city_info.get('country', 'Desconocido')
    flag_image = city_info.get('flag', '')

    lat, lon = city_info["lat"], city_info["lon"]

    conversor = city_conversor(city_name)

    # URL para Overpass API
    overpass_url = f'https://overpass-api.de/api/interpreter?data=[out:json];area[name="{conversor}"];node["tourism"]["tourism"!~"^(hotel|hostel|motel|picnic_site|camp_site|chalet|viewpoint|apartment|guest_house|attraction|gallery)$"](area);out;'

    response = requests.get(overpass_url)
    data = response.json() if response.status_code == 200 else {"elements": []}

    # Extraer los lugares turísticos
    places = []
    for elem in data["elements"]:
        if "lat" in elem and "lon" in elem:
            tags = elem.get("tags", {})
            places.append({
                "name": tags.get("name", "Lugar turístico"),
                "lat": elem["lat"],
                "lon": elem["lon"],
                "address": f'{tags.get("addr:street", "")} {tags.get("addr:housenumber", "")} {tags.get("addr:postcode", "")}'.strip(),
                "opening_hours": tags.get("opening_hours", "Horario no disponible"),
                "price": tags.get("fee", ""),
                "website": tags.get("website", ""),
                "phone": tags.get("phone", ""),
            })

    return render(request, "turism/city_map.html", {
        "city_name": city_name,
        "lat": lat,
        "lon": lon,
        "places": places,
        "country": country,
        "flag_image": flag_image,
        "complete_profile_alerts": complete_profile_alerts,
        "pending_requests_count": pending_requests_count,
        "pending_chat_requests_count": pending_chat_requests_count,
        "total_unread_count": total_unread_count,
    })

worldin/main/templates/community/create_chat.html
{% extends "main/sidebar.html" %}

{% block title %}Crear chat privado{% endblock %}

{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=NTR&family=Palanquin:wght@100;200;300;400;500;600;700&family=Work+Sans:wght@500&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Work Sans', sans-serif;
            color: #6a4fb8;
            overflow-x:hidden;
        }
        .profile-container {
            display: flex;
            flex-direction: column;
            max-width: 100%; /* Ocupar el máximo ancho disponible */
            padding: 0; /* Sin padding para que ocupe todo el ancho */
        }
        .profile-top {
            background-color: #6a4fb8;
            color: white;
            padding: 20px;
        }
        .search-users-container {
            background-color:rgb(241, 241, 241); /* Color de fondo para la lista de chats */
            height: 100%; /* Ajustar altura para toda la pantalla */
            padding: 15px;
            overflow-y: auto; /* Scroll si el contenido excede el tamaño */
        }
        .chat-container {
            display: flex;
            flex-direction: column;
            height: 100%; /* Ocupa toda la altura disponible */
        }
    
        .notification-bubble {
            background-color: #6a4fb8;
            color: white;
            border-radius: 30px;
            font-size: 16px;
            padding: 20px 20px;
            margin: 0;
            width: auto;
            display: inline-block;
        }
    
        /* Estilo del área de mensaje (textarea) */
        .form-control {
            border-radius: 20px;
            border: 2px solid #6a4fb8;
            padding: 15px;
            font-size: 16px;
            resize: none;
        }
    
        /* Estilo del botón de envío */
        button.btn {
            background-color: #6a4fb8;
            border-color: #6a4fb8;
            color: white;
            border-radius: 20px;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .profile-picture {
            border-radius: 50%;
            border: 4px solid #786dce;
            width: 50px;
            height: 50px;
            margin-right: 10px;
        }

        .action-buttons {
            display: flex;
            gap: 5px;
            margin-left: auto;
        }

        .selected {
            background-color:rgb(27, 17, 119) !important;
        }

        .input-group {
            width: auto;
        }

    </style>
</head>

<body>
    <div class="container profile-container">
        <div class="profile-top d-flex justify-content-between align-items-center">
            <div>
                <a href="{% url 'community:all_chats' %}" class="btn btn-secondary bi-arrow-left-short d-none d-md-block" style="background-color: transparent; border-color: white; font-size: 2em;">
                    <h3 style="font-size:12px;">Volver</h3>
                </a>
            </div>

            <div class="text-center">
                <h1><strong>Nuevo chat privado</strong></h1>
            </div>            
        </div>
        
        <div class="row">
            <!-- Buscador de usuarios -->
            <div class="col-md-7" style="height: 100vh;">
            <div class="search-users-container">
                <form method="GET" class="d-flex mt-5">
                <input type="text" name="q" placeholder="Buscar por nombre de usuario" style="height:45px; width: calc(100% - 120px); border: 2px solid #6a4fb8; background-color: #fff; box-shadow: 0px 0px 5px #6a4fb8; border-radius: 20px;" class="mr-2">
                <button type="submit" style="height: 45px; width: 100px; background-color: #6a4fb8; color: white; border: none; border-radius: 20px; padding: 10px 20px; cursor: pointer;">Buscar</button>
                </form>

                <ul class="list-group d-block mt-5">
                {% if users|length == 0 and request.GET.q %}
                    <li class="list-group-item">
                    <div style="text-align: center;">
                        <p style="display: inline;">No se encuentran usuarios para esta búsqueda.</p>
                        <a style="display: inline; text-decoration: underline;" href="{% url 'community:create_private_chat' %}">Reestablecer búsqueda</a>
                    </div>
                    </li>
                {% endif %}
                {% for user in users %}
                    <li class="list-group-item d-flex align-items-center">
                    <div class="user-info d-flex align-items-center">
                        {% if user.username == request.user.username %}
                        <a href="{% url 'my_profile' %}" style="text-decoration: none; color: #6a4fb8;">
                        {% else %}
                        <a href="{% url 'other_user_profile' user.username %}" style="text-decoration: none; color: #6a4fb8;">
                        {% endif %}
                        <div class="d-flex align-items-center">
                            {% if user.profile_picture %}
                                <img src="{{ user.profile_picture.url }}" class="profile-picture" alt="Perfil del cliente">
                            {% else %}
                                <img src="{% static 'images/default_user_icon_2.webp' %}" class="profile-picture" alt="Perfil del cliente">
                            {% endif %}
                            <div class="usuario-y-nombre ml-2">
                                <p style="font-size: 20px; margin-bottom: 0;"><strong>@{{ user.username }}</strong></p>
                                <p style="font-size: 16px; margin-bottom: 0;">{{ user.first_name }} {{ user.last_name }}</p>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="action-buttons ml-auto">
                        <form method="POST" id="user-{{ user.id }}-form">
                            {% csrf_token %}
                            <input type="hidden" name="selected_user" value="{{ user.id }}">
                            <button type="button" class="btn btn-primary select-user-btn" style="background-color:#786dce; color:white; border-color:white; font-size:20px;" onclick="selectUser({{ user.id }})">
                                SELECCIONAR
                            </button>
                        </form>
                    </div>
                    </li>
                    <hr class="dropdown-divider">
                {% endfor %}
                </ul>
            </div>
            </div>

            <div class="col-md-5">
            <div class="chat-container d-flex align-items-center">
                <h4 class="notification-bubble text-center mt-4">
                Manda un primer mensaje y espera a que el otro usuario acepte o rechace tu solicitud
                </h4>
                {% if error_messages %}
                <div class="alert alert-danger mt-4" style="font-size:18px;" role="alert">
                {% for message in error_messages %}
                    {{ message }}<br>
                {% endfor %}
                </div>
                {% endif %}
                <form method="POST" action="{% url 'community:create_private_chat' %}" class="d-flex align-items-center mt-4">
                {% csrf_token %}
                <input type="hidden" name="selected_user" id="selected_user_input">
                <div class="input-group flex-grow-1">
                    <input name="initial_message" id="initial_message" type="text" class="form-control" style="width:auto;" placeholder="Escribe un mensaje para iniciar la conversación...">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">
                            <i class="bi bi-send"></i>
                        </button>
                    </div>
                </div>
                </form>
            </div>
            </div>
        </div>
        
    </div>

        <script>

            function selectUser(userId) {
                // Actualiza el campo oculto con el id del usuario seleccionado
                document.getElementById('selected_user_input').value = userId;
                
                // Resalta el botón de selección y cambia su texto
                var buttons = document.querySelectorAll('.select-user-btn');
                buttons.forEach(function(button) {
                    button.classList.remove('selected');
                    button.textContent = 'SELECCIONAR';
                });

                var selectedButton = document.querySelector('#user-' + userId + '-form button');
                selectedButton.classList.add('selected');
                selectedButton.textContent = 'SELECCIONADO';
            }
        </script>
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                const input = document.getElementById("initial_message");
        
                // Crear un elemento invisible para medir el ancho del texto
                const measureSpan = document.createElement("span");
                measureSpan.style.visibility = "hidden";
                measureSpan.style.whiteSpace = "nowrap";
                measureSpan.style.font = window.getComputedStyle(input).font;
                document.body.appendChild(measureSpan);
        
                // Función para ajustar el ancho del input al placeholder
                function adjustInputWidth() {
                    measureSpan.textContent = input.placeholder;
                    input.style.width = `${measureSpan.offsetWidth + 40}px`; // Añadir un pequeño margen
                }
        
                // Ajustar inicialmente
                adjustInputWidth();
        
                // Limpieza
                window.addEventListener("unload", () => {
                    document.body.removeChild(measureSpan);
                });
            });
        </script>

</body>
{% endblock %}

worldin/main/templates/community/invalid_chat_creation.html
{% extends "main/sidebar.html" %}

{% block title %}Acceso no permitido{% endblock %}

{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=NTR&family=Palanquin:wght@100;200;300;400;500;600;700&family=Work+Sans:wght@500&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Work Sans', sans-serif;
            color: #6a4fb8;
            align-items: center;
            text-align: center;
        }
        .profile-container {
            
            max-width: 100%;
            padding: 0;
        }

        .profile-top {
            background-color: #6a4fb8;
            color: white;
            padding: 20px;
        }

        .profile-picture {
            width: 200px;
            height: 200px; /* Tamaño para pantallas más grandes */
        }

        @media (min-width: 768px) {
            .profile-picture {
                width: 400px;
                height: 400px; /* Tamaño para pantallas más grandes */
            }
        }

        
    </style>
</head>
<body>
    <div class="container profile-container">
        <div class="profile-top d-flex justify-content-between align-items-center">
            
        </div>
        <img src="{% static 'images/say-no.png' %}" class="profile-picture mt-5 mb-5" alt="Error 404 Not Found">
        <h1>Error 405: No puedes acceder a la página buscada</h1>
        <h3 class="mt-5">No está permitido crear un chat contigo mismo.</h3>
        <p>Por favor, elige un id de usuario válido.</p>
        <a href="{% url 'world' %}"><strong>Volver al mundo</strong></a>
        <div style="display:none;"> Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik"> Freepik </a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com'</a></div>
        

        
    </div>
</body>
{% endblock %}